// Better You — js/shared/auth.js
// Auto-generated by modularize.py

function selG(g){regG=g;document.getElementById('gbm').classList.toggle('on',g==='male');document.getElementById('gbf').classList.toggle('on',g==='female')}

function showErr(id,m){const e=document.getElementById(id);e.textContent=m;e.style.display='block'}

function hideErr(id){const e=document.getElementById(id);if(e)e.style.display='none'}

async function doReg(){
  hideErr('re-err');
  const n=document.getElementById('rn').value.trim(),e=document.getElementById('re').value.trim();
  const p=document.getElementById('rp').value,p2=document.getElementById('rp2').value,t=document.getElementById('tcb').checked;
  if(!n)return showErr('re-err','Please enter your full name.');
  if(!e.includes('@'))return showErr('re-err','Please enter a valid email address.');
  if(p.length<6)return showErr('re-err','Password must be at least 6 characters.');
  if(p!==p2)return showErr('re-err','Passwords do not match.');
  if(!t)return showErr('re-err','Please accept the Terms of Service.');
  try {
    await cloudSignUp(e, p, n, regG);
    await cloudLoadAll();
    const u = {name:n, email:e, gender:regG, isAdmin:false};
    loginUser(u);
    toast('Welcome to Better You!','party');
  } catch (err) {
    showErr('re-err', err.message || 'Registration failed. Please try again.');
  }
}

async function doLogin(){
  hideErr('le-err');
  const e=document.getElementById('le').value.trim(),p=document.getElementById('lp').value;
  if(!e||!p)return showErr('le-err','Please complete all fields.');
  try {
    await cloudSignIn(e, p);
    await cloudLoadAll();
    const u = {
      name: (_cloudProfile && _cloudProfile.name) || 
            (_cloudUser && _cloudUser.user_metadata && _cloudUser.user_metadata.name) || 
            e.split('@')[0],
      email: e,
      gender: (_cloudProfile && _cloudProfile.gender) || 'male',
      isAdmin: !!(_cloudProfile && _cloudProfile.is_admin)
    };
    loginUser(u);
    toast('Welcome back, '+u.name,'check');
  } catch (err) {
    showErr('le-err', err.message || 'Incorrect email or password.');
  }
}

function loginUser(u){
  user=u;ss('bn_session',u);
  exProg=gs('bn_exprog_'+u.email,{});
  difficulty=gs('bn_diff_'+u.email,'beginner');
  workoutOverrides=gs('bn_workout_overrides_'+u.email,{});
  customPlan=gs('bn_custom_plan_'+u.email,{days:{}});
  customExercises=gs('bn_custom_exercises_'+u.email,{});
  if(!gs('bn_week_'+u.email,''))ss('bn_week_'+u.email,getWeekKey());
  checkWeekReset();
  cpEditMode=false;
  updateNavUser();nav('dashboard');
}

async function signOut(){
  try { await cloudSignOut(); } catch {}
  user=null; updateNavUser();
  hView='day'; hDetailId=null; hSelDate=null; hForm=null; cpEditMode=false;
  nav('home'); toast('Signed out. See you tomorrow','logout');
}