// Better You — js/shared/navigation.js
// Auto-generated by modularize.py

const TAB_MAP = {
  home:      {loggedIn:'dashboard', guest:'home'},
  personal:  {loggedIn:'personal',  guest:'register'},
  spiritual: {loggedIn:'spiritual', guest:'register'},
  community: {loggedIn:'community', guest:'register'},
  more:      {loggedIn:'more',      guest:'about'}
};

const PAGE_TO_TAB = {
  dashboard:'home',
  home:'home',
  personal:'personal',
  spiritual:'spiritual',
  community:'community',
  more:'more',
  profile:'more',
  admin:'more',
  about:'more'
};

function switchTab(tabName){
  const tab = TAB_MAP[tabName];
  if (!tab) return;
  const target = user ? tab.loggedIn : tab.guest;
  nav(target);
  setActiveTab(tabName);
}

function setActiveTab(tabName){
  document.querySelectorAll('#tab-bar .tab-btn').forEach(btn => {
    btn.classList.toggle('on', btn.dataset.tab === tabName);
  });
}

function updateTabBarVisibility(){
  const tb = document.getElementById('tab-bar');
  if (!tb) return;
  tb.style.display = 'flex';
  tb.classList.toggle('guest', !user);
}

function nav(pg){
  if (user && (pg === 'home' || pg === 'login' || pg === 'register')) {
    pg = 'dashboard';
  }
  const tabName = PAGE_TO_TAB[pg];
  if (tabName) setActiveTab(tabName);

  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
  const el=document.getElementById('pg-'+pg);if(el)el.classList.add('active');
  window.scrollTo(0,0);closeMob();closeDD();
  if(pg==='dashboard')renderDash();
  if(pg==='personal')renderPersonal();
  if(pg==='community')renderComm();
  if(pg==='profile')renderProfile();
  if(pg==='admin')renderAdmin();
}

function grd(pg){user?nav(pg):nav('login')}

function commNav(){user?nav('community'):nav('register')}

function toggleMob(){const mn=document.getElementById('mob-nav');if(mn)mn.classList.toggle('open')}

function closeMob(){const mn=document.getElementById('mob-nav');if(mn)mn.classList.remove('open')}

function toggleDD(e){if(e)e.stopPropagation();const dd=document.getElementById('prof-dd');if(dd)dd.classList.toggle('open')}

function closeDD(){const dd=document.getElementById('prof-dd');if(dd)dd.classList.remove('open')}
document.addEventListener('click',e=>{
  const dd=document.getElementById('prof-dd');
  const av=document.getElementById('nav-av');
  if(dd&&!dd.contains(e.target)&&!(av&&av.contains(e.target)))closeDD();
  const mob=document.getElementById('mob-nav');
  const hb=document.querySelector('.hbg');
  if(mob&&mob.classList.contains('open')&&!mob.contains(e.target)&&!(hb&&hb.contains(e.target)))closeMob();
});
window.addEventListener('scroll',()=>document.getElementById('navbar').classList.toggle('scrolled',scrollY>28));

function toggleTheme(){
  const d=document.documentElement,dark=d.getAttribute('data-theme')==='dark';
  const nt=dark?'light':'dark';d.setAttribute('data-theme',nt);
  const btn=document.getElementById('theme-btn');if(btn)btn.innerHTML=ico(nt==='dark'?'moon':'sun',16);
  ss('bn_theme',nt);
}

function updateNavUser(){
  const li = !!user;

  document.getElementById('nav-guest').style.display = li ? 'none' : 'block';
  document.getElementById('nav-user').style.display  = li ? 'block' : 'none';

  const setVis = (id, show) => {
    const el = document.getElementById(id);
    if (el) el.style.display = show ? '' : 'none';
  };
  setVis('nav-home',      !li);
  setVis('nav-dash',       li);
  setVis('nav-personal',   li);
  setVis('nav-spiritual',  li);
  setVis('nav-community',  li);
  setVis('mob-home',      !li);
  setVis('mob-dash',       li);
  setVis('mob-personal',   li);
  setVis('mob-spiritual',  li);
  setVis('mob-community',  li);
  setVis('mob-join',      !li);

  if (user) {
    const i = user.name.charAt(0).toUpperCase();
    document.getElementById('nav-av').textContent = i;
    const sa = document.getElementById('sb-av'); if (sa) sa.textContent = i;
    const sn = document.getElementById('sb-name'); if (sn) sn.textContent = user.name;

    const ddAv = document.getElementById('dd-av'); if (ddAv) ddAv.textContent = i;
    const ddNm = document.getElementById('dd-name'); if (ddNm) ddNm.textContent = user.name;
    const ddRl = document.getElementById('dd-role'); if (ddRl) ddRl.textContent = user.isAdmin ? 'Administrator' : 'Better You Member';

    const al = document.getElementById('dd-admin'); if (al) al.style.display = user.isAdmin ? 'flex' : 'none';
    const sal = document.getElementById('sb-admin'); if (sal) sal.style.display = user.isAdmin ? 'flex' : 'none';
    const ma = document.getElementById('more-admin'); if (ma) ma.style.display = 'flex';
    const mus = document.getElementById('more-user-section'); if (mus) mus.style.display = 'block';

    const ns = document.getElementById('nav-streak');
    if (ns) ns.style.display = 'inline-flex';
    const nsn = document.getElementById('nav-streak-num');
    if (nsn) {
      const newVal = '7';
      const oldVal = nsn.textContent;
      nsn.textContent = newVal;
      if (oldVal !== newVal && oldVal !== '0' && oldVal !== '' && ns) {
        setTimeout(() => streakJump(ns), 300);
      }
    }
  } else {
    const ma = document.getElementById('more-admin'); if (ma) ma.style.display = 'none';
    const mus = document.getElementById('more-user-section'); if (mus) mus.style.display = 'none';
    const ns = document.getElementById('nav-streak'); if (ns) ns.style.display = 'none';
  }
  updateTabBarVisibility();
}