// Better You — js/shared/state.js
// Auto-generated by modularize.py

let greetingTimer = null;

let activeHabitList = [];

let habitIdx = 0;

let habitRotTimer = null;

let user=null,exProg={},regG='male',commPosts=[...COMM_SEED];

let tSec=0,tTotal=0,tInt=null,timerOnEnd=null;

let selDay=new Date().getDay(),difficulty='beginner',activeExIdx=-1;

let ytFilterTier='all';

let workoutOverrides={};

let customPlan={days:{}};

let customExercises={};

let cePickerDay=null,cePickerTab='library',cePickerSearch='',ceEditId=null,_ceMode='reps';

let cpLongTimer=null,cpMenuRef=null,cpMenuDay=null,cpEditMode=false;

let ytLinks=gs('bn_yt_links',{});

let hView='day',hDetailId=null,hSelDate=null,hForm=null,hFormMode='create',hLogHabitId=null,hLongPressTimer=null,hMenuHabitId=null;