// Better You — js/shared/ui.js
// Auto-generated by modularize.py

function previewToast(msg){
  if(typeof toast === 'function'){ toast(msg, 'check'); return; }
  let el = document.getElementById('preview-toast');
  if(!el){
    el = document.createElement('div');
    el.id = 'preview-toast';
    el.style.cssText = 'position:fixed;bottom:96px;left:50%;transform:translate(-50%,80px);background:#1c1812;border:1px solid rgba(217,174,74,.4);border-radius:14px;padding:12px 22px;font-family:Inter,sans-serif;font-size:13px;color:#F0E8D8;opacity:0;transition:all .35s cubic-bezier(.22,1,.36,1);pointer-events:none;z-index:9999;box-shadow:0 8px 32px rgba(0,0,0,.5)';
    document.body.appendChild(el);
  }
  el.textContent = msg;
  el.style.transform = 'translate(-50%, 0)';
  el.style.opacity = '1';
  clearTimeout(window._toastT);
  window._toastT = setTimeout(() => {
    el.style.transform = 'translate(-50%, 80px)';
    el.style.opacity = '0';
  }, 2200);
}

function toast(msg,ic='check'){const el=document.getElementById('toast-el');document.getElementById('t-msg').textContent=msg;document.getElementById('t-ico').innerHTML=ico(ic,15);el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3300)}

function glowCard(el,type){el.classList.remove('glow-green-top','glow-yellow-top');void el.offsetWidth;el.classList.add(type==='green'?'glow-green-top':'glow-yellow-top');setTimeout(()=>el.classList.remove('glow-green-top','glow-yellow-top'),800)}

function glowTop(el,type){el.classList.remove('glow-green-top','glow-yellow-top');void el.offsetWidth;el.classList.add(type==='green'?'glow-green-top':'glow-yellow-top');setTimeout(()=>el.classList.remove('glow-green-top','glow-yellow-top'),800)}

function streakJump(el){
  if(!el) return;
  el.classList.remove('jump');
  void el.offsetWidth;
  el.classList.add('jump');
  if(navigator.vibrate) navigator.vibrate(20);
  setTimeout(() => el.classList.remove('jump'), 1000);
}

function celebrateHabit(el,color){
  if(!el)return;
  const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;
  const palette=[color,'#D9AE4A','#DDBB6B','#ffffff','#7BA8E8'];
  for(let i=0;i<14;i++){
    const p=document.createElement('div');p.className='habit-burst';
    const angle=(i/14)*Math.PI*2+(Math.random()-0.5)*0.6;
    const dist=38+Math.random()*38,dx=Math.cos(angle)*dist,dy=Math.sin(angle)*dist-32;
    const sz=4+Math.random()*4;
    p.style.cssText=`left:${cx}px;top:${cy}px;background:${palette[Math.floor(Math.random()*palette.length)]};width:${sz}px;height:${sz}px;--dx:${dx}px;--dy:${dy}px`;
    document.body.appendChild(p);setTimeout(()=>p.remove(),950);
  }
}