// Better You — js/shared/utilities.js
// Auto-generated by modularize.py

function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function parseReps(reps){
  const m=(reps||'').match(/^(\d+)\s*×\s*(\d+(?:\.\d+)?)(.*)$/);
  if(!m)return null;
  return {sets:parseInt(m[1],10),repsPerSet:parseFloat(m[2]),suffix:m[3]||''};
}

function animC(el,target){if(!el||isNaN(target))return;let c=0;const step=Math.ceil(target/55);const t=setInterval(()=>{c=Math.min(c+step,target);el.textContent=c.toLocaleString();if(c>=target)clearInterval(t)},22)}

const counted=new Set();

function todayStr(){return fmtDate(new Date())}

function fmtDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}

function parseDate(s){const p=s.split('-').map(Number);return new Date(p[0],p[1]-1,p[2])}

function addDays(s,n){const d=parseDate(s);d.setDate(d.getDate()+n);return fmtDate(d)}

function dayName(s){return DAY_FULL[parseDate(s).getDay()]}

function isLightColor(hex){const c=hex.replace('#','');const r=parseInt(c.substr(0,2),16),g=parseInt(c.substr(2,2),16),b=parseInt(c.substr(4,2),16);return (0.299*r+0.587*g+0.114*b)/255>0.62}

function distributeEvenly(count,range){const s=[];for(let i=0;i<count;i++)s.push(Math.floor(i*range/count));return s}

function fmt12(t){if(!t)return'';const[H,M]=t.split(':').map(Number);const ampm=H>=12?'PM':'AM';const h12=H%12||12;return h12+':'+String(M).padStart(2,'0')+' '+ampm}

// Better You — js/pages/_misc.js
// Auto-generated by modularize.py

const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting&&!counted.has(e.target)){counted.add(e.target);animC(e.target,parseInt(e.target.getAttribute('data-count')))}})},{threshold:.3});
document.querySelectorAll('.cnt').forEach(el=>io.observe(el));