// Better You — js/pages/admin.js
// Auto-generated by modularize.py

async function renderAdmin(){
  const tb=document.getElementById('admin-users-tb');if(!tb)return;
  try {
    const us = await cloudGetAllProfiles();
    tb.innerHTML = us.length
      ? us.map(u=>`<tr><td>${escapeHtml(u.name)}</td><td>${escapeHtml(u.email)}</td><td><span style="background:rgba(217,174,74,.12);color:var(--acc);border-radius:20px;padding:2px 9px;font-size:10px;font-weight:700">${u.is_admin?'Admin':'Active'}</span></td></tr>`).join('')
      : `<tr><td colspan="3" style="text-align:center;color:var(--txt2);padding:20px">No registered users yet</td></tr>`;
  } catch {
    tb.innerHTML = `<tr><td colspan="3" style="text-align:center;color:var(--txt2);padding:20px">Could not load users</td></tr>`;
  }
  renderYTManager();
  document.querySelectorAll('#panel-adash .cnt').forEach(el=>animC(el,parseInt(el.getAttribute('data-count'))));
}

function renderYTManager(){
  const cont=document.getElementById('yt-manager-list');if(!cont)return;
  const allEx=[];
  ['beginner','intermediate','professional'].forEach(tier=>{
    Object.values(WORKOUTS[tier]).forEach(day=>{if(day.exs)day.exs.forEach(ex=>allEx.push({...ex,tierLabel:tier,dayLabel:day.label}))});
  });
  const filtered=allEx.filter(ex=>ytFilterTier==='all'||ex.tierLabel===ytFilterTier);
  cont.innerHTML=filtered.map(ex=>{
    const saved=ytLinks[ex.id]||'';
    return `<div class="yt-ex-card" id="ytc-${ex.id}"><div class="yt-ex-name">${escapeHtml(ex.name)}</div><div class="yt-ex-meta">${ex.tierLabel} · ${ex.dayLabel} · ${ex.reps}</div><div class="yt-input-row"><input class="yt-input" id="yt-${ex.id}" placeholder="YouTube embed ID" value="${saved}"/><button class="yt-save-btn" onclick="saveYT('${ex.id}')">Save</button><button class="btn bg-b bsm" onclick="previewYT('${ex.id}')">Preview</button></div><div class="yt-preview" id="ytprev-${ex.id}"><iframe src="" allowfullscreen loading="lazy"></iframe></div></div>`;
  }).join('');
}

function saveYT(exId){const inp=document.getElementById('yt-'+exId);if(!inp)return;let id=inp.value.trim();const m=id.match(/(?:v=|embed\/|youtu\.be\/)([a-zA-Z0-9_-]{11})/);if(m)id=m[1];ytLinks[exId]=id;ss('bn_yt_links',ytLinks);toast('YouTube link saved','play')}

function previewYT(exId){const inp=document.getElementById('yt-'+exId);if(!inp)return;let id=inp.value.trim();const m=id.match(/(?:v=|embed\/|youtu\.be\/)([a-zA-Z0-9_-]{11})/);if(m)id=m[1];const prev=document.getElementById('ytprev-'+exId);if(!prev)return;if(!id){toast('Enter a YouTube ID first','warning');return}prev.style.display='block';prev.querySelector('iframe').src='https://www.youtube.com/embed/'+id+'?rel=0'}

function filterYTTier(tier,btn){ytFilterTier=tier;document.querySelectorAll('.tier-filter .tf-btn').forEach(b=>b.classList.remove('on'));btn.classList.add('on');renderYTManager()}

function renderAdminPublicList(){
  const cont=document.getElementById('admin-public-list');if(!cont)return;
  const allUsers=gs('bn_users',{});
  const merged={};
  Object.keys(allUsers).forEach(email=>{
    const exs=gs('bn_custom_exercises_'+email,{});
    Object.keys(exs).forEach(id=>{merged[id]={...exs[id],_owner:allUsers[email].name||email}});
  });
  if(user){
    const myEx=gs('bn_custom_exercises_'+user.email,{});
    Object.keys(myEx).forEach(id=>{merged[id]={...myEx[id],_owner:user.name}});
  }
  const pub=getPublicExercises();
  const keys=Object.keys(merged);
  if(!keys.length){cont.innerHTML='<div style="padding:30px;text-align:center;color:var(--txt2);font-size:13px">No user-created exercises found yet.</div>';return}
  cont.innerHTML=keys.map(id=>{
    const ce=merged[id];
    const pubId='pe_'+id.replace(/^ce_/,'');
    const isPub=!!pub[pubId];
    return `<div class="ce-public-row"><div style="flex:1;min-width:0"><div class="ce-public-name">${escapeHtml(ce.name)} <span style="font-size:10px;color:var(--txt2);font-weight:400">· ${escapeHtml(ce._owner||'')}</span></div><div class="ce-public-meta">${escapeHtml(ceModeLabel(ce))}</div></div><button class="btn bp bsm" onclick="adminPushPublic('${id}')" ${isPub?'style="opacity:.5" disabled':''}>${isPub?'Published':'Push to Public'}</button></div>`;
  }).join('');
}

function adminPushPublic(id){
  const allUsers=gs('bn_users',{});
  let ce=null;
  Object.keys(allUsers).forEach(email=>{const exs=gs('bn_custom_exercises_'+email,{});if(exs[id])ce=exs[id]});
  if(!ce&&user){const exs=gs('bn_custom_exercises_'+user.email,{});if(exs[id])ce=exs[id]}
  if(!ce){toast('Exercise not found','warning');return}
  const pub=getPublicExercises();
  const pubId='pe_'+id.replace(/^ce_/,'');
  pub[pubId]={...ce,id:pubId,publishedBy:user?.name||'Admin',publishedAt:Date.now()};
  savePublicExercises(pub);
  toast('Exercise published to community','party');
  renderAdminPublicList();
}

function aPanel(id,e){
  document.querySelectorAll('.ap').forEach(p=>p.classList.remove('on'));
  document.querySelectorAll('.admin-sb .sbl').forEach(l=>l.classList.remove('on'));
  const p=document.getElementById('panel-'+id);if(p)p.classList.add('on');
  if(e?.currentTarget)e.currentTarget.classList.add('on');
  if(id==='apublic')renderAdminPublicList();
}