// Better You — js/pages/boot.js
// Auto-generated by modularize.py

(()=>{const t=gs('bn_theme','dark');document.documentElement.setAttribute('data-theme',t);const btn=document.getElementById('theme-btn');if(btn){btn.innerHTML=ico(t==='dark'?'moon':'sun',16);btn.removeAttribute('data-icon')}})();

(async function boot() {
  document.body.classList.add('booting');

  await cloudInitSession(async (isLoggedIn) => {
    if (isLoggedIn && _cloudUser) {
      const u = {
        name: (_cloudProfile && _cloudProfile.name) || 
              (_cloudUser.user_metadata && _cloudUser.user_metadata.name) || 
              _cloudUser.email.split('@')[0],
        email: _cloudUser.email,
        gender: (_cloudProfile && _cloudProfile.gender) || 'male',
        isAdmin: !!(_cloudProfile && _cloudProfile.is_admin)
      };
      user = u;
      exProg = gs('bn_exprog_' + u.email, {});
      difficulty = gs('bn_diff_' + u.email, 'beginner');
      workoutOverrides = gs('bn_workout_overrides_' + u.email, {});
      customPlan = gs('bn_custom_plan_' + u.email, {days:{}});
      customExercises = gs('bn_custom_exercises_' + u.email, {});
      if (!gs('bn_week_' + u.email, '')) ss('bn_week_' + u.email, getWeekKey());
      checkWeekReset();
      updateNavUser();
      document.body.classList.remove('booting');
      nav('dashboard');
    } else {
      document.body.classList.remove('booting');
      nav('home');
    }
  });
})();