// Better You — js/pages/community.js
// Auto-generated by modularize.py

function renderComm(){
  if(!user)return;
  const ca=document.getElementById('comm-av');if(ca)ca.textContent=user.name.charAt(0).toUpperCase();
  renderFeed();renderMembers();
}

function renderFeed(){
  const el=document.getElementById('comm-feed');if(!el)return;
  el.innerHTML=commPosts.map(p=>{
    const cs=p.comments.map(c=>`<div class="cb-item"><div class="cb-auth">${typeof c==='object'?c.a:'Member'}</div><div class="cb-txt">${typeof c==='object'?c.t:c}</div></div>`).join('');
    const own=p.author===user?.name;
    return `<div class="post-card" id="pc-${p.id}"><div class="ph"><div class="pav" style="background:${p.col}">${p.init}</div><div><div class="pnm">${p.author}</div><div class="ptm">${p.time}</div></div></div><div class="pbody">${escapeHtml(p.text)}</div><div class="rr"><button class="rb${p.mine==='l'?' on':''}" onclick="react(${p.id},'l')">${ico('thumbs-up',13)} ${p.r.l}</button><button class="rb${p.mine==='f'?' on':''}" onclick="react(${p.id},'f')">${ico('fire',13)} ${p.r.f}</button><button class="rb${p.mine==='h'?' on':''}" onclick="react(${p.id},'h')">${ico('heart',13)} ${p.r.h}</button><button class="rb${p.mine==='c'?' on':''}" onclick="react(${p.id},'c')">${ico('clap',13)} ${p.r.c}</button></div><div class="pa"><button class="pab" onclick="toggleCB(${p.id})">Comment</button>${own?`<button class="pab danger" onclick="delPost(${p.id})">Delete</button>`:''}</div><div class="cb-box" id="cb-${p.id}"><div class="cb-row"><input class="cb-inp" id="ci-${p.id}" placeholder="Write a reply..." onkeydown="if(event.key==='Enter')submitC(${p.id})"/><button class="cb-send" onclick="submitC(${p.id})">Send</button></div><div class="cb-list">${cs}</div></div></div>`;
  }).join('');
}

function createPost(){const ta=document.getElementById('post-input');const t=ta.value.trim();if(!t)return toast('Please write something.','warning');const cols=['#D9AE4A','#DDBB6B','#B8902F','#A87719','#F5E6C0'];commPosts.unshift({id:Date.now(),author:user.name,init:user.name.charAt(0).toUpperCase(),col:cols[Math.floor(Math.random()*cols.length)],text:t,time:'Just now',r:{l:0,f:0,h:0,c:0},mine:null,comments:[]});ta.value='';renderFeed();toast('Shared!','rocket')}

function react(id,type){const p=commPosts.find(p=>p.id===id);if(!p)return;if(p.mine===type){p.r[type]--;p.mine=null}else{if(p.mine)p.r[p.mine]--;p.r[type]++;p.mine=type}renderFeed()}

function toggleCB(id){const el=document.getElementById('cb-'+id);if(el){el.style.display=el.style.display==='block'?'none':'block';document.getElementById('ci-'+id)?.focus()}}

function submitC(id){const inp=document.getElementById('ci-'+id);if(!inp)return;const t=inp.value.trim();if(!t)return;const p=commPosts.find(p=>p.id===id);if(!p)return;p.comments.push({a:user.name,t});renderFeed();setTimeout(()=>{const cb=document.getElementById('cb-'+id);if(cb)cb.style.display='block'},50)}

function delPost(id){if(!confirm('Delete this post?'))return;commPosts=commPosts.filter(p=>p.id!==id);renderFeed();toast('Deleted','trash')}

function renderMembers(){const el=document.getElementById('top-members');if(!el)return;const ms=[{n:'Amara O.',s:21,c:'#D9AE4A'},{n:'David M.',s:18,c:'#B8902F'},{n:'Sarah K.',s:15,c:'#A87719'}];el.innerHTML=ms.map(m=>`<div class="mi"><div class="mav" style="background:${m.c};color:${m.c==='#B8902F'||m.c==='#D9AE4A'?'#111':'#fff'}">${m.n.charAt(0)}</div><div><div class="mn">${m.n}</div><div class="ms">${ico('fire',11)} ${m.s}-day streak</div></div></div>`).join('')}