// Better You — js/pages/dashboard.js
// Auto-generated by modularize.py

function getTimeBucket(){
  const h = new Date().getHours();
  return (h >= 5 && h < 12) ? 'morning'
       : (h >= 12 && h < 17) ? 'afternoon'
       : (h >= 17 && h < 22) ? 'evening'
       : 'night';
}

function pickGreeting(){
  const pool = GREETINGS[getTimeBucket()];
  let last = null;
  try { last = sessionStorage.getItem('bn_last_greet'); } catch {}
  const options = pool.filter(g => g !== last);
  const pick = options[Math.floor(Math.random() * options.length)] || pool[0];
  try { sessionStorage.setItem('bn_last_greet', pick); } catch {}
  return pick;
}

function animateGreeting(text){
  const el = document.getElementById('hg-label');
  if(!el) return;
  el.innerHTML = '';
  text.split('').forEach((ch, i) => {
    if(ch === ' '){
      const s = document.createElement('span');
      s.className = 'hw-space';
      s.innerHTML = '&nbsp;';
      el.appendChild(s);
      return;
    }
    const span = document.createElement('span');
    span.className = 'hw-char';
    span.textContent = ch;
    span.style.animationDelay = (i * 42) + 'ms';
    el.appendChild(span);
  });
}

function startGreetingRotation(){
  clearInterval(greetingTimer);
  greetingTimer = setInterval(() => {
    if (document.visibilityState === 'visible') {
      animateGreeting(pickGreeting());
    }
  }, 20000);
}

function getTodayHabits(){
  if(!user) return [];
  const today = todayStr();
  return getHabits().filter(h => isHabitScheduledOn(h, today));
}

function getHabitsDoneToday(){
  if(!user) return [];
  const today = todayStr();
  const logs = getHabitLogs();
  return getTodayHabits().filter(h => {
    const log = logs[hLogKey(h.id, today)];
    return log && log.status === 'completed';
  });
}

function updateHabitCount(){
  const total = getTodayHabits().length;
  const done  = getHabitsDoneToday().length;
  const el = document.getElementById('pd-count');
  if(!el) return;
  if(total === 0) el.textContent = 'No habits today';
  else el.textContent = done + ' of ' + total + ' done';
}

function setHabitDisplay(idx){
  const list = activeHabitList;
  const h = list[idx];
  const nameEl = document.getElementById('pd-habit-name');
  const statusEl = document.getElementById('pd-status');
  if(!nameEl || !statusEl) return;

  if(!h){
    nameEl.textContent = 'All done for today';
    statusEl.className = 'pd-status done';
    statusEl.textContent = '✓';
    return;
  }

  nameEl.textContent = h.name;
  const today = todayStr();
  const log = getHabitLog(h.id, today);
  const isDone = log && log.status === 'completed';

  if(isDone){
    statusEl.className = 'pd-status done';
    statusEl.textContent = '✓';
  } else {
    statusEl.className = 'pd-status pending';
    statusEl.textContent = '?';
  }
}

function initHabitRotation(){
  activeHabitList = getTodayHabits();
  habitIdx = 0;
  const today = todayStr();
  activeHabitList.sort((a, b) => {
    const aDone = getHabitLog(a.id, today)?.status === 'completed' ? 1 : 0;
    const bDone = getHabitLog(b.id, today)?.status === 'completed' ? 1 : 0;
    return aDone - bDone;
  });
  setHabitDisplay(0);
}

function startHabitRotation(){
  clearInterval(habitRotTimer);
  habitRotTimer = setInterval(() => {
    if (document.visibilityState !== 'visible') return;
    if (!activeHabitList.length) return;
    const lineEl = document.getElementById('pd-habit-line');
    if(!lineEl) return;
    lineEl.classList.add('fading');
    setTimeout(() => {
      habitIdx = (habitIdx + 1) % activeHabitList.length;
      setHabitDisplay(habitIdx);
      lineEl.classList.remove('fading');
    }, 400);
  }, 6000);
}

function getBiblePlan(){
  if(!user) return DEFAULT_BIBLE_PLAN;
  return gs('bn_bible_plan_' + user.email, DEFAULT_BIBLE_PLAN);
}

function renderSpiritualCard(){
  const plan = getBiblePlan();
  const chapterEl = document.getElementById('duo-spiritual-chapter');
  const titleEl   = document.getElementById('duo-spiritual-title');
  const valEl     = document.getElementById('duo-progress-val');
  const fillEl    = document.getElementById('duo-progress-fill');
  const btnEl     = document.getElementById('duo-spiritual-btn-label');

  if(chapterEl) chapterEl.textContent = (plan.book + ' ' + plan.chapter).toUpperCase();
  if(titleEl)   titleEl.textContent   = plan.chaptersRead > 0 ? 'Continue Bible' : 'Begin Bible';
  if(valEl)     valEl.textContent     = plan.chaptersRead + '/' + plan.totalChapters;
  if(fillEl)    fillEl.style.width    = Math.min(100, (plan.chaptersRead / plan.totalChapters) * 100) + '%';
  if(btnEl)     btnEl.textContent     = plan.chaptersRead > 0 ? 'Continue' : 'Begin';
}

function getTodayWorkout(){
  const day  = new Date().getDay();
  const diff = difficulty === 'custom' ? 'beginner' : difficulty;
  return WORKOUTS[diff]?.[day] || WORKOUTS.beginner[day];
}

function renderSessionCard(){
  const w = getTodayWorkout();
  if(!w) return;
  const metaEl  = document.getElementById('session-meta');
  const titleEl = document.getElementById('session-title');

  if(metaEl){
    if(w.isRest){
      metaEl.textContent = 'REST DAY · RECOVERY';
    } else {
      const exCount = (w.exs || []).length;
      metaEl.textContent = w.tag.toUpperCase() + ' · ' + exCount + ' EXERCISES · 25 MIN';
    }
  }
  if(titleEl){
    titleEl.textContent = w.isRest ? w.tag : (w.tag + ' Session');
  }
}

function openPersTab(tab){
  if(!user) return;
  const labels = {
    workout:    'Opening Workouts',
    skills:     'Opening Life Skills',
    habits:     'Opening Habits',
    books:      'Opening Books',
    challenges: 'Opening Challenges'
  };
  previewToast(labels[tab] || 'Opening Personal');
  if(navigator.vibrate) navigator.vibrate(10);
  setTimeout(() => {
    nav('personal');
    setTimeout(() => {
      const btn = document.querySelector('#pg-personal .sbl[data-tab="' + tab + '"]');
      if(btn) showPersTab(tab, btn);
    }, 80);
  }, 260);
}

function openSpiritualTab(tab){
  if(!user) return;
  const labels = {
    bible:      'Opening Bible Reading',
    prayer:     'Opening Prayer Journal',
    devotionals:'Opening Devotionals',
    scripture:  'Opening Scripture',
    spbooks:    'Opening Spiritual Books'
  };
  previewToast(labels[tab] || 'Opening Spiritual');
  if(navigator.vibrate) navigator.vibrate(10);
  setTimeout(() => {
    nav('spiritual');
    setTimeout(() => {
      const btn = document.querySelector('#pg-spiritual .sbl[data-tab="' + tab + '"]');
      if(btn) showSpiritualTab(btn);
    }, 80);
  }, 260);
}

function startTodayWorkout(){
  const w = getTodayWorkout();
  if(!w) return;
  if(w.isRest){
    previewToast('Rest day — recovery is progress');
    return;
  }
  previewToast("Starting today's workout");
  if(navigator.vibrate) navigator.vibrate(20);
  setTimeout(() => {
    nav('personal');
    setTimeout(() => {
      const btn = document.querySelector('#pg-personal .sbl[data-tab="workout"]');
      if(btn) showPersTab('workout', btn);
      selDay = new Date().getDay();
      activeExIdx = -1;
      buildWeekTabs();
      renderExCards();
      startSession();
    }, 100);
  }, 300);
}

function bookmarkVerse(){
  if(!user) return;
  const v = WORD_VERSES[new Date().getDay() % WORD_VERSES.length];
  const saved = gs('bn_saved_verses_' + user.email, []);
  if(saved.find(x => x.ref === v.ref && x.text === v.text)){
    previewToast('Already saved');
    return;
  }
  saved.unshift({ ...v, savedAt: Date.now() });
  ss('bn_saved_verses_' + user.email, saved);
  if(navigator.vibrate) navigator.vibrate(15);
  previewToast('Verse saved');
}

function shareVerse(){
  const v = WORD_VERSES[new Date().getDay() % WORD_VERSES.length];
  const text = v.text + ' — ' + v.ref;
  if(navigator.share){
    navigator.share({ title: 'Verse of the Day', text }).catch(() => {});
  } else if(navigator.clipboard){
    navigator.clipboard.writeText(text).then(() => previewToast('Verse copied'));
  } else {
    previewToast('Sharing not supported');
  }
}

function pulseSpiritualBtn(){
  const btn = document.getElementById('duo-spiritual-btn');
  if(!btn) return;
  btn.classList.remove('btn-pulse');
  void btn.offsetWidth;
  btn.classList.add('btn-pulse');
  if(navigator.vibrate) navigator.vibrate(15);
  setTimeout(() => {
    btn.classList.remove('btn-pulse');
    openSpiritualTab('bible');
  }, 550);
}

function renderDash(){
  if (!user) return;
  seedDefaultHabits();
  const now = new Date();

  // Greeting
  animateGreeting(pickGreeting());
  const nameEl = document.getElementById('hg-name');
  if (nameEl) nameEl.textContent = (user.name || 'Friend').toUpperCase();
  const dateEl = document.getElementById('hg-date');
  if (dateEl) {
    dateEl.textContent = now.toLocaleDateString('en-US',{
      weekday:'long', month:'long', day:'numeric'
    });
  }

  // Hero time-of-day palette
  const heroCard = document.getElementById('hero-card');
  if (heroCard) heroCard.setAttribute('data-time', getTimeBucket());

  // Verse of the day
  const v = WORD_VERSES[now.getDay() % WORD_VERSES.length];
  const wText = document.getElementById('word-text');
  const wRef  = document.getElementById('word-ref');
  if (wText) wText.textContent = v.text;
  if (wRef)  wRef.textContent  = v.ref;

  // Push
  const p = PUSH_QUOTES[now.getDay() % PUSH_QUOTES.length];
  const pQuote  = document.getElementById('push-quote');
  const pAuthor = document.getElementById('push-author');
  if (pQuote)  pQuote.textContent  = p.quote;
  if (pAuthor) pAuthor.textContent = p.author;

  // Live data from the rest of the system
  renderSpiritualCard();
  updateHabitCount();
  initHabitRotation();
  renderSessionCard();
}

(function initHeroBurst() {
  const card = document.getElementById('hero-card');
  if (!card) return;
  const ambient = card.querySelector('.hero-ambient');
  if (!ambient) return;

  let holdTimer = null;
  let holdStart = 0;
  let activeParticles = 0;

  function spawnBurst(count, heldMs) {
    for (let i = 0; i < count; i++) {
      if (activeParticles > 180) return;
      const p = document.createElement('span');
      p.className = 'burst-dust';
      p.style.left = (4 + Math.random() * 92) + '%';
      p.style.setProperty('--bx', (Math.random() * 80 - 40) + 'px');
      p.style.animationDuration = (4.5 + Math.random() * 2) + 's';
      const size = Math.min(11, 4 + heldMs / 500);
      p.style.width = size + 'px';
      p.style.height = size + 'px';
      activeParticles++;
      p.addEventListener('animationend', () => {
        activeParticles--;
        p.remove();
      }, { once: true });
      ambient.appendChild(p);
    }
  }

  function startHold(e) {
    if (e.pointerType === 'mouse' && e.button !== 0) return;
    holdStart = Date.now();
    spawnBurst(5, 0);
    if (navigator.vibrate) navigator.vibrate(10);
    clearInterval(holdTimer);
    holdTimer = setInterval(() => {
      const held = Date.now() - holdStart;
      let count = 1;
      if (held > 3000) count = 4;
      else if (held > 1500) count = 3;
      else if (held > 600) count = 2;
      spawnBurst(count, held);
    }, 200);
  }

  function endHold() {
    clearInterval(holdTimer);
    holdTimer = null;
  }

  card.addEventListener('pointerdown', startHold);
  card.addEventListener('pointerup', endHold);
  card.addEventListener('pointercancel', endHold);
  card.addEventListener('pointerleave', endHold);
})();

(function initDuoCardReact() {
  const cards = document.querySelectorAll('.duo-card');
  if (cards.length < 2) return;

  function applyShift(tappedCard) {
    cards.forEach(c => {
      if (c === tappedCard) c.style.transform = 'translateY(-3px)';
      else c.style.transform = 'translateY(3px)';
    });
  }

  cards.forEach(card => {
    card.addEventListener('pointerdown', () => applyShift(card));
  });
})();

startGreetingRotation();
startHabitRotation();

// ── Service Worker Registration ──
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js')
      .then(reg => console.log('✓ Service worker registered:', reg.scope))
      .catch(err => console.warn('Service worker registration failed:', err));
  });
}