// Better You — js/pages/personal.js
// Auto-generated by modularize.py

function buildWeekTabs(){
  const cont=document.getElementById('week-tabs');if(!cont)return;
  const today=new Date().getDay();
  if(difficulty==='custom'){
    const plan=getCustomPlan();
    cont.innerHTML=[0,1,2,3,4,5,6].map(d=>{
      const day=plan.days?.[d];
      const hasEx=day&&day.exs&&day.exs.length>0;
      const lbl=DAY_FULL[d];
      const tag=hasEx?day.exs.length+' exercise'+(day.exs.length>1?'s':''):'Empty';
      const isToday=d===today;
      return `<button class="wt${d===selDay?' on':''}${!hasEx?' rest-d':''}" onclick="selectDay(${d})">${lbl.slice(0,3)}<span style="font-size:9px;display:block;font-weight:400;opacity:.7">${tag}${isToday?' ·Now':''}</span></button>`;
    }).join('');
    return;
  }
  cont.innerHTML=[0,1,2,3,4,5,6].map(d=>{
    const w=WORKOUTS[difficulty][d];if(!w)return '';
    const isToday=d===today;
    return `<button class="wt${d===selDay?' on':''}${w.isRest?' rest-d':''}" onclick="selectDay(${d})">${w.label.slice(0,3)}<span style="font-size:9px;display:block;font-weight:400;opacity:.7">${w.tag}${isToday?' ·Now':''}</span></button>`;
  }).join('');
}

function selectDay(d){selDay=d;activeExIdx=-1;buildWeekTabs();renderExCards()}

function updateWorkoutHeaderBtns(){
  const isCustom=difficulty==='custom';
  const editBtn=document.getElementById('workout-edit-plan-btn');
  const doneBtn=document.getElementById('workout-done-edit-btn');
  const copyBtn=document.getElementById('workout-copy-btn');
  const delBtn=document.getElementById('workout-delete-plan-btn');
  if(editBtn)editBtn.style.display=(isCustom&&!cpEditMode)?'inline-flex':'none';
  if(doneBtn)doneBtn.style.display=(isCustom&&cpEditMode)?'inline-flex':'none';
  if(copyBtn)copyBtn.style.display=(isCustom&&cpEditMode)?'inline-flex':'none';
  if(delBtn)delBtn.style.display=(isCustom&&cpEditMode)?'inline-flex':'none';
}

function setDiff(d,btn){
  difficulty=d;
  if(user)ss('bn_diff_'+user.email,d);
  document.querySelectorAll('.diff-btn').forEach(b=>b.classList.remove('on'));
  btn.classList.add('on');
  activeExIdx=-1;
  if(d!=='custom')cpEditMode=false;
  updateWorkoutHeaderBtns();
  buildWeekTabs();
  renderExCards();
}

function renderPersonal(){
  if(!user)return;
  if(checkWeekReset())toast('New week — workout progress reset','refresh');
  document.querySelectorAll('.diff-btn').forEach(b=>b.classList.remove('on'));
  const diffMap={'beginner':'diff-b','intermediate':'diff-i','professional':'diff-p','custom':'diff-c'};
  const db=document.getElementById(diffMap[difficulty]);if(db)db.classList.add('on');
  selDay=new Date().getDay();
  activeExIdx=-1;
  updateWorkoutHeaderBtns();
  buildWeekTabs();
  renderExCards();
  renderSkillsGrid('pers-skills-grid');
  hView='day';renderHabits();
}

function showPersTab(t,btn){
  document.querySelectorAll('#pg-personal .dash-tab').forEach(el=>el.classList.remove('on'));
  const el=document.getElementById('pt-'+t);if(el)el.classList.add('on');
  document.querySelectorAll('#pg-personal .sbl').forEach(b=>b.classList.remove('on'));
  if(btn)btn.classList.add('on');
  if(t==='skills')renderSkillsGrid('pers-skills-grid');
  if(t==='habits'){hView='day';renderHabits()}
}

function showSpiritualTab(btn){
  document.querySelectorAll('#pg-spiritual .sbl').forEach(b=>b.classList.remove('on'));
  if(btn)btn.classList.add('on');
}