// Better You — js/pages/profile.js
// Auto-generated by modularize.py

function renderProfile(){
  if(!user)return;
  const n=document.getElementById('prof-name');if(n)n.textContent=user.name;
  const a=document.getElementById('prof-av');if(a)a.textContent=user.name.charAt(0).toUpperCase();
  const cal=document.getElementById('prof-cal');if(!cal)return;
  const today=new Date().getDate();
  const done=[1,2,3,5,6,7,8,9,12,13,14,15,16,19,20,21,22,23];
  cal.innerHTML=Array.from({length:31},(_,i)=>i+1).map(d=>`<div class="cc${done.includes(d)?' done':''}${d===today?' today-c':''}">${d}</div>`).join('');
}