// Better You — js/pages/skills.js
// Auto-generated by modularize.py

function renderSkillsGrid(targetId){
  const el=document.getElementById(targetId);if(!el)return;
  el.innerHTML=LIFE_SKILLS.map(s=>`<div class="ls-box" onclick="glowTop(this,'green');toast('Opening ${s.name}','${s.icon}')"><div class="ls-ico"><span data-icon="${s.icon}" data-size="24" style="color:var(--acc)"></span></div><div class="ls-cat-label">${s.cat}</div><div class="ls-nm">${s.name}</div><div class="ls-desc">${s.desc}</div></div>`).join('');
  hydrateIcons(el);
}