// Better You — js/pages/workouts.js
// Auto-generated by modularize.py

function getWeekKey(){
  const d=new Date(),day=d.getDay();
  const sunday=new Date(d);sunday.setDate(d.getDate()-day);
  return sunday.getFullYear()+'-'+String(sunday.getMonth()+1).padStart(2,'0')+'-'+String(sunday.getDate()).padStart(2,'0');
}

function checkWeekReset(){
  if(!user)return false;
  const storedWeek=gs('bn_week_'+user.email,''),currentWeek=getWeekKey();
  if(storedWeek!==currentWeek){
    exProg={};ss('bn_exprog_'+user.email,exProg);ss('bn_week_'+user.email,currentWeek);
    const locks=gs('bn_session_'+user.email,{});
    Object.keys(locks).forEach(k=>{if(!k.startsWith(currentWeek+'_'))delete locks[k]});
    ss('bn_session_'+user.email,locks);return true;
  }
  return false;
}

function sessionKey(d){return getWeekKey()+'_'+difficulty+'_'+d}

function isSessionLocked(d){if(!user)return false;const m=gs('bn_session_'+user.email,{});return !!m[sessionKey(d)]}

function lockSession(d){if(!user)return;const m=gs('bn_session_'+user.email,{});m[sessionKey(d)]=true;ss('bn_session_'+user.email,m)}

function normalizeCustomExercise(ce){
  const mode=ce.mode||'reps';
  let valText;
  if(mode==='reps')valText=ce.repsPerSet||0;
  else if(mode==='time')valText=(ce.secondsPerSet||0)+' sec';
  else valText=(ce.distancePerSet||0)+(ce.unit||'');
  return {
    id:ce.id,name:ce.name||'Custom Exercise',sets:ce.sets||3,
    reps:(ce.sets||3)+' × '+valText+(ce.suffix||''),
    howto:ce.howto||'',focus:ce.focus||'',ytId:ce.ytId||'',
    _isCustom:true,_mode:mode,_unit:ce.unit||'',_editable:true
  };
}

function resolveRef(refId){
  if(!refId)return null;
  if(refId.indexOf('ce_')===0){const ce=customExercises[refId];return ce?normalizeCustomExercise(ce):null}
  if(refId.indexOf('pe_')===0){const ce=getPublicExercises()[refId];return ce?normalizeCustomExercise(ce):null}
  for(const tier of ['beginner','intermediate','professional']){
    for(const d of Object.values(WORKOUTS[tier])){
      if(d.exs){const found=d.exs.find(e=>e.id===refId);if(found)return found}
    }
  }
  return null;
}

function exerciseStoreKey(ex){return ex._storeKey||ex.id}

function applyOverride(base){
  const p=parseReps(base.reps);if(!p)return base;
  const ov=workoutOverrides[base.id]||{};
  const sets=ov.sets!=null?ov.sets:p.sets;
  const repsPerSet=ov.repsPerSet!=null?ov.repsPerSet:p.repsPerSet;
  return {...base,sets,reps:sets+' × '+repsPerSet+p.suffix,_baseSets:p.sets,_baseRepsPerSet:p.repsPerSet,_repsPerSet:repsPerSet,_suffix:p.suffix,_editable:true};
}

function getDayExercises(diff,dayNum){
  if(diff==='custom'){
    const plan=getCustomPlan();
    const day=plan.days?.[dayNum];
    if(!day||!day.exs||!day.exs.length)return [];
    return day.exs.map(ref=>{
      const r=resolveRef(ref);if(!r)return null;
      return {...r,_storeKey:'cp'+dayNum+'_'+ref,_refId:ref};
    }).filter(Boolean).map(applyOverride);
  }
  const day=WORKOUTS[diff]?.[dayNum];
  if(!day||!day.exs)return [];
  return day.exs.map(applyOverride);
}

function saveWorkoutOverrides(){if(!user)return;ss('bn_workout_overrides_'+user.email,workoutOverrides)}

function renderExEditPanel(ex){
  const mode=ex._mode||'reps';
  let lbl='Reps per set',step=5;
  if(mode==='time'){lbl='Seconds per set';step=5}
  if(mode==='distance'){lbl='Distance per set';step=1}
  return `<div class="ex-edit-panel" id="exedit-${ex.id}">
    <div class="ex-edit-row">
      <div class="ex-edit-lbl">Sets</div>
      <div class="ex-edit-stepper">
        <button class="ex-edit-step-btn" onclick="event.stopPropagation();exEditStep('${ex.id}','sets',-1)">−</button>
        <div class="ex-edit-val" id="exedit-${ex.id}-sets">${ex.sets}</div>
        <button class="ex-edit-step-btn" onclick="event.stopPropagation();exEditStep('${ex.id}','sets',1)">+</button>
      </div>
    </div>
    <div class="ex-edit-row">
      <div class="ex-edit-lbl">${lbl}</div>
      <div class="ex-edit-stepper">
        <button class="ex-edit-step-btn" onclick="event.stopPropagation();exEditStep('${ex.id}','reps',-${step})">−</button>
        <div class="ex-edit-val" id="exedit-${ex.id}-reps">${ex._repsPerSet!=null?ex._repsPerSet:10}</div>
        <button class="ex-edit-step-btn" onclick="event.stopPropagation();exEditStep('${ex.id}','reps',${step})">+</button>
      </div>
    </div>
    <div class="ex-edit-actions">
      <button class="btn bg-b bsm" onclick="event.stopPropagation();exEditReset('${ex.id}')">Reset</button>
      <button class="btn bp bsm" onclick="event.stopPropagation();exEditSave('${ex.id}')">Save</button>
    </div>
  </div>`;
}

function toggleExEdit(id){
  const el=document.getElementById('exedit-'+id);if(!el)return;
  const isOpen=el.style.display==='block';
  document.querySelectorAll('.ex-edit-panel').forEach(p=>p.style.display='none');
  if(!isOpen)el.style.display='block';
}

function exEditStep(id,field,delta){
  const el=document.getElementById('exedit-'+id+'-'+(field==='sets'?'sets':'reps'));if(!el)return;
  let v=parseInt(el.textContent,10)||0;v+=delta;
  if(field==='sets')v=Math.max(1,Math.min(20,v));
  else{
    const lbl=el.closest('.ex-edit-row')?.querySelector('.ex-edit-lbl')?.textContent||'';
    if(lbl.indexOf('Distance')!==-1)v=Math.max(1,Math.min(1000,v));
    else if(lbl.indexOf('Seconds')!==-1)v=Math.max(5,Math.min(600,v));
    else v=Math.max(5,Math.min(200,v));
  }
  el.textContent=v;
}

function exEditSave(id){
  const setsEl=document.getElementById('exedit-'+id+'-sets');
  const repsEl=document.getElementById('exedit-'+id+'-reps');
  if(!setsEl||!repsEl)return;
  const sets=parseInt(setsEl.textContent,10);
  const repsPerSet=parseInt(repsEl.textContent,10);
  workoutOverrides[id]={sets,repsPerSet};saveWorkoutOverrides();
  if(exProg[id]&&Array.isArray(exProg[id].sets)){exProg[id].sets=exProg[id].sets.filter(i=>i<sets);if(user)ss('bn_exprog_'+user.email,exProg)}
  document.querySelectorAll('.ex-edit-panel').forEach(p=>p.style.display='none');
  renderExCards();toast('Exercise updated','check');
}

function exEditReset(id){
  delete workoutOverrides[id];saveWorkoutOverrides();
  document.querySelectorAll('.ex-edit-panel').forEach(p=>p.style.display='none');
  renderExCards();toast('Reverted to default','refresh');
}

function renderExerciseCardHTML(ex,idx,exs,locked,isCustomPlan){
  const storeKey=exerciseStoreKey(ex);
  const s=exProg[storeKey]||{sets:[],done:false};
  const isActive=idx===activeExIdx,isDone=s.done,isFirst=idx===0,isLast=idx===exs.length-1;
  const pct=ex.sets>0?Math.round((s.sets.length/ex.sets)*100):0;
  const setsHtml=ex.sets>0?Array.from({length:ex.sets},(_,i)=>`<button class="sbt${s.sets.includes(i)?' done':''}" onclick="tickSet('${storeKey}',${i},${idx})">${s.sets.includes(i)?ico('check',14):i+1}</button>`).join(''):'';
  const ytId=ex.ytId||ytLinks[ex.id]||'';
  const videoHtml=ytId?`<div class="ex-video-wrap"><iframe src="https://www.youtube.com/embed/${ytId}?rel=0" allowfullscreen loading="lazy"></iframe></div>`:`<div style="background:var(--bg3);border-radius:10px;padding:14px;margin-bottom:12px;text-align:center"><a href="https://www.youtube.com/results?search_query=${encodeURIComponent(ex.name+' exercise tutorial')}" target="_blank" style="color:var(--acc);font-size:12px;font-weight:700;text-decoration:none;display:inline-flex;align-items:center;gap:5px">${ico('search',13)} Search "${escapeHtml(ex.name)}" on YouTube</a></div>`;
  const canEdit=ex._editable&&!locked&&!isDone&&(!isCustomPlan||cpEditMode);
  const editBtn=canEdit?`<button class="ex-edit-btn" onclick="event.stopPropagation();toggleExEdit('${ex.id}')" title="Edit sets & reps">${ico('edit',13)}</button>`:'';
  const editPanel=canEdit?renderExEditPanel(ex):'';
  const lpAttrs=(isCustomPlan&&cpEditMode)?`onpointerdown="cpCardDown(event,'${ex._refId}',${selDay})" onpointerup="cpCardUp()" onpointerleave="cpCardUp()" onpointercancel="cpCardUp()" oncontextmenu="event.preventDefault();cpMenuOpen(event,'${ex._refId}',${selDay})"`:'';
  const tagText=difficulty==='custom'?'My Plan':difficulty.charAt(0).toUpperCase()+difficulty.slice(1);
  if(isDone){
    return `<div class="ex-card ex-done" id="exc-${ex.id}" ${lpAttrs}><div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><div class="ex-done-check">${ico('check',14)}</div><div><div class="ex-nm">${escapeHtml(ex.name)}</div><div class="ex-reps-txt">${ex.reps} · ${ex.sets} sets · Complete</div></div></div>${isLast&&!locked?`<button class="session-done-btn" onclick="openCong()">${ico('party',16)} Session Completed!</button>`:''}</div>`;
  }
  if(isActive){
    const allSetsDone=ex.sets>0&&s.sets.length>=ex.sets;
    return `<div class="ex-card ex-active" id="exc-${ex.id}" ${lpAttrs}>
      <div class="ex-card-hdr" style="display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:10px">
        <div style="flex:1;min-width:0"><div class="ex-nm">${escapeHtml(ex.name)}</div><div class="ex-reps-txt">${ex.reps} · ${ex.sets} sets · <span style="color:var(--acc);font-weight:700">ACTIVE</span></div></div>
        <div style="display:flex;align-items:center;gap:8px;flex-shrink:0">${editBtn}<span class="ex-tag">${tagText}</span><button class="ex-complete-check${allSetsDone?' done':''}" onclick="completeAllSets('${storeKey}',${idx})" aria-label="Complete all sets">${ico('check',20)}</button></div>
      </div>
      ${ex.howto?`<div class="ex-desc-box"><strong>How to do it:</strong> ${escapeHtml(ex.howto)}</div>`:''}
      ${ex.focus?`<div class="ex-focus-box"><div class="ex-focus-lbl">Focus on</div><div class="ex-focus-txt">${escapeHtml(ex.focus)}</div></div>`:''}
      ${videoHtml}
      <div style="display:flex;justify-content:space-between;font-size:11px;color:var(--txt2);margin-bottom:4px"><span>Set progress</span><span style="color:var(--acc)">${s.sets.length}/${ex.sets}</span></div>
      <div class="pt" style="margin-bottom:8px"><div class="pf" style="width:${pct}%"></div></div>
      <div class="sets-row">${setsHtml}</div>${editPanel}
    </div>`;
  }
  if(isFirst&&activeExIdx===-1&&!isDone){
    return `<div class="ex-card" id="exc-${ex.id}" ${lpAttrs}><div style="display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px"><div class="ex-nm">${escapeHtml(ex.name)}</div>${editBtn}</div><div class="ex-reps-txt" style="margin-bottom:12px">${ex.reps} · ${ex.sets} sets</div><button class="start-btn" onclick="startSession()">${ico('play',13)} Start Session</button>${editPanel}</div>`;
  }
  return `<div class="ex-card ex-locked" id="exc-${ex.id}" ${lpAttrs}><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:10px"><div style="flex:1;min-width:0"><div class="ex-nm">${escapeHtml(ex.name)}</div><div class="ex-reps-txt">${ex.reps} · ${ex.sets} sets</div><div class="ex-locked-msg">Complete the previous exercise to unlock</div></div>${editBtn}</div>${editPanel}</div>`;
}

function renderExCards(){
  const cont=document.getElementById('pers-ex-cards');if(!cont)return;
  if(difficulty==='custom'){renderCustomExCards(cont);return}
  const tod=WORKOUTS[difficulty][selDay];if(!tod){cont.innerHTML='';return}
  if(tod.isRest){cont.innerHTML=`<div class="rest-card"><div class="rest-leaf">${ico('leaf',36)}</div><h4 style="margin-bottom:8px">${tod.tag}</h4><p style="font-size:13px;color:var(--txt2);font-weight:400;line-height:1.7">${tod.restDesc}</p></div>`;return}
  const exs=getDayExercises(difficulty,selDay);
  const locked=isSessionLocked(selDay);
  cont.innerHTML=exs.map((ex,idx)=>renderExerciseCardHTML(ex,idx,exs,locked,false)).join('');
  hydrateIcons(cont);
}

function renderCustomExCards(cont){
  const exs=getDayExercises('custom',selDay);
  const locked=isSessionLocked(selDay);
  const edit=cpEditMode;
  const plan=getCustomPlan();
  const anyExs=Object.values(plan.days||{}).some(d=>d.exs&&d.exs.length>0);
  if(!exs.length){
    if(edit){
      cont.innerHTML=`<div class="cp-empty-hero">
        <div class="cp-empty-title">${anyExs?'Rest Day':'Build Your Plan'}</div>
        <div class="cp-empty-desc">${anyExs?'No exercises scheduled for '+DAY_FULL[selDay]+'. Add some below.':'Add exercises to each day, or copy a template to get started.'}</div>
        ${!anyExs?`<div class="cp-copy-row">
          <button class="cp-copy-btn" onclick="cpCopyFrom('beginner')">Copy Beginner</button>
          <button class="cp-copy-btn" onclick="cpCopyFrom('intermediate')">Copy Intermediate</button>
          <button class="cp-copy-btn" onclick="cpCopyFrom('professional')">Copy Professional</button>
        </div>`:''}
      </div>
      <button class="cp-day-add" onclick="cePickerOpen(${selDay})">${ico('plus',14)} Add Exercise</button>`;
    }else{
      cont.innerHTML=`<div class="cp-empty-hero">
        <div class="cp-empty-title">${anyExs?'Rest Day':'No plan yet'}</div>
        <div class="cp-empty-desc">${anyExs?'No exercises scheduled for '+DAY_FULL[selDay]+'. Tap Edit Plan above to change.':'Tap Edit Plan above to start building your custom workout plan.'}</div>
      </div>`;
    }
    hydrateIcons(cont);return;
  }
  const cardsHtml=exs.map((ex,idx)=>renderExerciseCardHTML(ex,idx,exs,locked,true)).join('');
  cont.innerHTML=cardsHtml+(edit?`<button class="cp-day-add" onclick="cePickerOpen(${selDay})">${ico('plus',14)} Add Exercise</button>`:'');
  hydrateIcons(cont);
}

function startSession(){
  activeExIdx=0;renderExCards();
  setTimeout(()=>{const exs=getDayExercises(difficulty,selDay);const el=document.getElementById('exc-'+exs[0]?.id);if(el)el.scrollIntoView({behavior:'smooth',block:'nearest'})},100);
}

function completeAllSets(storeKey,exArrIdx){
  const s=exProg[storeKey]||{sets:[],done:false};
  const exs=getDayExercises(difficulty,selDay);
  const ex=exs[exArrIdx];if(!ex)return;
  if(s.sets.length>=ex.sets)return;
  s.sets=Array.from({length:ex.sets},(_,i)=>i);exProg[storeKey]={...s};
  if(user)ss('bn_exprog_'+user.email,exProg);
  renderExCards();
  const isLastEx=exArrIdx===exs.length-1;
  if(ex.noTimer){markExDone(storeKey,exArrIdx);return}
  openTimer(60,isLastEx?'Last Exercise Done!':'Exercise Complete!',isLastEx?'Take your rest — then tap Session Completed!':'1 minute rest before the next exercise.',()=>{markExDone(storeKey,exArrIdx)});
}

function tickSet(storeKey,setIdx,exArrIdx){
  const s=exProg[storeKey]||{sets:[],done:false};
  if(s.sets.includes(setIdx)){s.sets=s.sets.filter(i=>i!==setIdx);exProg[storeKey]={...s};if(user)ss('bn_exprog_'+user.email,exProg);renderExCards();return}
  s.sets=[...s.sets,setIdx];exProg[storeKey]={...s};
  if(user)ss('bn_exprog_'+user.email,exProg);
  const exs=getDayExercises(difficulty,selDay);
  const ex=exs[exArrIdx];if(!ex)return;
  const totalSets=ex.sets;
  const isLastSet=s.sets.length>=totalSets;
  const isLastEx=exArrIdx===exs.length-1;
  renderExCards();
  if(isLastSet){
    if(ex.noTimer){markExDone(storeKey,exArrIdx);return}
    openTimer(60,isLastEx?'Last Exercise Done!':'Exercise Complete!',isLastEx?'Take your rest — then tap Session Completed!':'1 minute rest before the next exercise.',()=>{markExDone(storeKey,exArrIdx)});
  }else{
    if(ex.noTimer)return;
    openTimer(30,'Rest Between Sets','30 seconds — next up: set '+(s.sets.length+1)+' of '+totalSets,null);
  }
}

function markExDone(storeKey,exArrIdx){
  const s=exProg[storeKey]||{sets:[],done:false};
  exProg[storeKey]={...s,done:true};
  if(user)ss('bn_exprog_'+user.email,exProg);
  const exs=getDayExercises(difficulty,selDay);
  const isLast=exArrIdx===exs.length-1;
  if(!isLast)activeExIdx=exArrIdx+1;
  renderExCards();
  if(!isLast){setTimeout(()=>{const nextEl=document.getElementById('exc-'+exs[exArrIdx+1]?.id);if(nextEl)nextEl.scrollIntoView({behavior:'smooth',block:'nearest'})},100)}
}

function resetWorkout(){
  if(!confirm('Reset all workout progress for this week?'))return;
  exProg={};
  if(user){
    ss('bn_exprog_'+user.email,exProg);
    const locks=gs('bn_session_'+user.email,{});
    const prefix=getWeekKey()+'_';
    Object.keys(locks).forEach(k=>{if(k.startsWith(prefix))delete locks[k]});
    ss('bn_session_'+user.email,locks);
  }
  activeExIdx=-1;renderExCards();renderDash();
  toast('Workout reset for the week','refresh');
}

function openTimer(sec,title,sub,onEnd){
  clearInterval(tInt);tTotal=sec;tSec=sec;timerOnEnd=onEnd||null;
  document.getElementById('tt').innerHTML=ico('clock',16)+' '+title;
  document.getElementById('ts2').textContent=sub||'1 minute rest between sets';
  updTimer();document.getElementById('timer-ov').classList.add('open');
  tInt=setInterval(()=>{tSec--;if(tSec<=0){clearInterval(tInt);closeTimerAndRun()}else updTimer()},1000);
}

function updTimer(){
  const m=Math.floor(tSec/60),s=tSec%60;
  document.getElementById('t-num').textContent=m+':'+(s<10?'0'+s:s);
  document.getElementById('t-pl').textContent=tSec+' second'+(tSec!==1?'s':'')+' remaining';
  const pct=tSec/tTotal;
  document.getElementById('t-arc').style.strokeDashoffset=CIRC*(1-pct);
}

function closeTimerAndRun(){document.getElementById('timer-ov').classList.remove('open');if(timerOnEnd){const fn=timerOnEnd;timerOnEnd=null;fn()}}

function closeTimer(){clearInterval(tInt);document.getElementById('timer-ov').classList.remove('open')}

function skipTimer(){clearInterval(tInt);closeTimerAndRun()}

function timerAdd(n){tSec+=n;tTotal+=n;updTimer();toast('+'+n+' sec added','clock')}

function logSession(){
  if(!user)return;
  const d=new Date(),dstr=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
  const key='bn_history_'+user.email;
  const history=gs(key,[]);
  const exs=getDayExercises(difficulty,selDay);
  const done=exs.filter(ex=>exProg[exerciseStoreKey(ex)]?.done).length;
  const total=exs.length;if(total===0)return;
  const already=history.find(h=>h.date===dstr&&h.day===selDay&&h.difficulty===difficulty);
  if(already){already.exercisesCompleted=done;already.totalExercises=total;already.timestamp=Date.now()}
  else history.push({date:dstr,day:selDay,difficulty,exercisesCompleted:done,totalExercises:total,timestamp:Date.now()});
  ss(key,history);lockSession(selDay);
}

function openCong(){
  logSession();
  const ov=document.getElementById('cong-ov');ov.classList.add('open');
  const box=document.getElementById('cong-box');
  const cols=['#D9AE4A','#DDBB6B','#B8902F','#A87719','#F5E6C0'];
  for(let i=0;i<20;i++){
    const c=document.createElement('div');c.className='confetti';
    c.style.cssText=`left:${Math.random()*100}%;top:${-25+Math.random()*40}px;background:${cols[Math.floor(Math.random()*cols.length)]};width:${5+Math.random()*6}px;height:${5+Math.random()*6}px;animation-delay:${Math.random()*1.5}s;animation-duration:${2.5+Math.random()*1.5}s;border-radius:${Math.random()>.5?'50%':'2px'}`;
    box.appendChild(c);setTimeout(()=>c.remove(),5000);
  }
}

function closeCong(){document.getElementById('cong-ov').classList.remove('open');renderExCards()}